CREATE TABLE USERTASK (
    ID int NOT NULL AUTO_INCREMENT,
    USER_NAME varchar(255),
    PASSWORD varchar(255),
    MAIL_ADDRESS varchar(255) UNIQUE,
    ROLE varchar(255),
    STATUS varchar(255),
    LAST_MODIFIED date,
    CREATED date,
    PRIMARY KEY (ID));

CREATE TABLE TASK (
    ID int NOT NULL AUTO_INCREMENT,
    TITLE varchar(255),
    TICKET_NUMBER varchar(255) NOT NULL UNIQUE,
    STATUS varchar(255),
    DESCRIPTION varchar(255),
    LAST_MODIFIED date,
    CREATED date,
    USER_ID int,
    PRIMARY KEY (ID),
    CONSTRAINT FK_ASSIGNTASK FOREIGN KEY (USER_ID)
    REFERENCES USERTASK(ID));

INSERT INTO TASK (TITLE, TICKET_NUMBER, STATUS, DESCRIPTION, LAST_MODIFIED, CREATED, USER_ID)
    VALUES ('Request Approval 1', 'ABC_01', 'TO_DO', 'Description 1', null, now(), null);
INSERT INTO TASK (TITLE, TICKET_NUMBER, STATUS, DESCRIPTION, LAST_MODIFIED, CREATED, USER_ID)
    VALUES ('Request Approval 2', 'ABC_02', 'TO_DO', 'Description 2', null, now(), null);

INSERT INTO USERTASK (USER_NAME, PASSWORD, MAIL_ADDRESS, ROLE, STATUS, LAST_MODIFIED, CREATED)
    VALUES ('TONY', 'ADMIN@GMAIL.COM', null, 'SUPER_ADMIN', 'ACTIVE', now(), now());
INSERT INTO USERTASK (USER_NAME, PASSWORD, MAIL_ADDRESS, ROLE, STATUS, LAST_MODIFIED, CREATED)
    VALUES ('USER 2', 'USER2@GMAIL.COM', null, 'ADMIN', 'ACTIVE', now(), now());